CREATE SCHEMA IF NOT EXISTS pcs_dags_manager;

CREATE TABLE IF NOT EXISTS pcs_dags_manager.managed_dag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dag_id VARCHAR(250) NOT NULL UNIQUE,
    template_key VARCHAR(128) NOT NULL,
    github_path TEXT NOT NULL UNIQUE,
    current_values JSONB NOT NULL,
    state VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    latest_commit_sha VARCHAR(64),
    created_by VARCHAR(250),
    updated_by VARCHAR(250),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_managed_dag_template_key
    ON pcs_dags_manager.managed_dag (template_key);

CREATE TABLE IF NOT EXISTS pcs_dags_manager.dag_revision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    managed_dag_id BIGINT NOT NULL REFERENCES pcs_dags_manager.managed_dag(id) ON DELETE CASCADE,
    revision_no INTEGER NOT NULL,
    action VARCHAR(16) NOT NULL,
    values JSONB NOT NULL,
    rendered_sha256 VARCHAR(64) NOT NULL,
    github_commit_sha VARCHAR(64),
    created_by VARCHAR(250),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_dag_revision_managed_dag_revision UNIQUE (managed_dag_id, revision_no)
);

CREATE INDEX IF NOT EXISTS ix_dag_revision_managed_dag_id
    ON pcs_dags_manager.dag_revision (managed_dag_id);
